In [6]:
#Indexing
import numpy as np
arr = np.array([3,4,5,6,7,8])
print(arr[3])

6


In [13]:
arr = np.array([[3,4,5],[6,8,7]])
arr[0][2]

5

In [25]:
arr = np.array([[[3,4,5],[7,7,7]],[[4,5,3],[6,5,1]]])
print(arr[1][0][2])
print(arr[0][1][0])


3
7


In [26]:
#slicing

arr = np.array([3,4,5,6,7,8])
arr[:3]

array([3, 4, 5])

In [31]:
arr = np.array([[3,4,5],[6,8,7]])

arr[0:, ::2]

array([[3, 5],
       [6, 7]])

In [36]:
arr = np.array([[[3,4,5],[7,7,7]],[[4,5,3],[6,5,1]]])
arr[0:, 0:, 2]

array([[5, 7],
       [3, 1]])