In [1]:
import numpy as np

arr = np.array([2,3,4,5])
arr1 = np.array([4,5,6,7])

print(np.add(arr, arr1))

[ 6  8 10 12]


In [2]:
np.subtract(arr,arr1)

array([-2, -2, -2, -2])

In [3]:
np.multiply(arr, arr1)

array([ 8, 15, 24, 35])

In [4]:
np.divide(arr,arr1)

array([0.5       , 0.6       , 0.66666667, 0.71428571])

In [5]:
np.power(arr,arr1)

array([   16,   243,  4096, 78125])

In [9]:
data = np.genfromtxt("grocery.csv", delimiter = ",", dtype = None , encoding = "utf-8",skip_header = 1 )
products = data["f0"]
price = data["f1"]
quantity = data['f2']
print(products)
print(price)
print(quantity)

['Apples' 'Bananas' 'Carrots' 'Tomatoes' 'Potatoes' 'Onions' 'Broccoli'
 'Spinach' 'Milk' 'Eggs' 'Bread' 'Chicken Breast' 'Ground Beef' 'Salmon'
 'Yogurt' 'Cheese' 'Orange Juice' 'Coffee' 'Rice' 'Pasta']
[ 1.99  0.59  0.89  2.49  1.29  0.79  2.19  1.99  3.49  2.99  2.49  5.99
  6.99 10.99  0.99  4.49  3.99  9.99  1.49  1.29]
[150 200 250 180 300 270 130 220 190 160  80  60  50  40 300 230 120  70
 500 450]


In [10]:
np.sum(quantity)

3950

In [11]:
print(arr)
print(arr1)

[2 3 4 5]
[4 5 6 7]


In [13]:
np.sum([arr, arr1], axis = 0)

array([ 6,  8, 10, 12])

In [15]:
np.sum([price, quantity], axis =  1) 

array([  67.4, 3950. ])

In [ ]:
#axis 1 = vertical 
#axis 0 = horizontal

In [16]:
print(price)
print(quantity)

[ 1.99  0.59  0.89  2.49  1.29  0.79  2.19  1.99  3.49  2.99  2.49  5.99
  6.99 10.99  0.99  4.49  3.99  9.99  1.49  1.29]
[150 200 250 180 300 270 130 220 190 160  80  60  50  40 300 230 120  70
 500 450]


In [17]:
sales = np.product([price, quantity], axis = 0)
print(sales)

[ 298.5  118.   222.5  448.2  387.   213.3  284.7  437.8  663.1  478.4
  199.2  359.4  349.5  439.6  297.  1032.7  478.8  699.3  745.   580.5]


In [18]:
np.cumsum(sales)

array([ 298.5,  416.5,  639. , 1087.2, 1474.2, 1687.5, 1972.2, 2410. ,
       3073.1, 3551.5, 3750.7, 4110.1, 4459.6, 4899.2, 5196.2, 6228.9,
       6707.7, 7407. , 8152. , 8732.5])