In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

a = [2,3,4]

arr = np.array(a)
print(arr)

[2 3 4]


In [4]:
a = [2,3,4]
b = [4,5,6]

print(a+b)

[2, 3, 4, 4, 5, 6]


In [7]:
arr1 = np.array(a)
arr2 = np.array(b)
print(arr1-arr2)

[-2 -2 -2]


In [10]:
arr = np.array([2,3,4,"5.6",7])
print(arr)

['2' '3' '4' '5.6' '7']


In [18]:
a = [2,3,4,5]
arr = np.array(a)
print(arr.dtype)
print(type(arr))

int32
<class 'numpy.ndarray'>


In [24]:
arr = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
print(arr)
print(arr.ndim)

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]
3
